from insta.task_parsers.json_task_parser import (
    JsonTaskParser
)


SYSTEM_PROMPT = """You are helping me design tasks for a language model agent that interacts with and navigates live webpages."""


USER_PROMPT_TEMPLATE = """Design a challenging task for {website} based on the agent's trajectory.

{summary}"""


class SimplifiedJsonTaskParser(JsonTaskParser):
    """Implements a parser for converting text generated by an LLM into a
    task for an LLM agent to attempt to complete using a web browser,
    returns a BrowserJudgment instance parsed from the response.

    Attributes:

    system_prompt: str
        Depending on the task representation, this system prompt
        instructs the LLM on how to generate tasks in the corresponding format,
        such as JSON-based tasks, YAML format, etc.

    user_prompt_template: str
        A template string that is used to generate a user prompt for the LLM,
        and has format keys for `annotations` which represents
        previous task runs and judgments produced by the LLM judge.

    """

    system_prompt = SYSTEM_PROMPT
    user_prompt_template = USER_PROMPT_TEMPLATE
