from insta.judgment_parsers.json_judgment_parser import (
    JsonJudgmentParser
)


SYSTEM_PROMPT = """You are helping me evaluate a language model agent that interacts with and navigates live webpages."""


USER_PROMPT_TEMPLATE = """Determine if the agent has completed its task.

{instruction}

Here is the agent's trajectory.

{summary}"""


class SimplifiedJsonJudgmentParser(JsonJudgmentParser):
    """Implements a parser for converting text generated by an LLM into a
    judgment of whether a web browsing task has been successfully completed,
    returns a BrowserJudgment instance parsed from the response.

    Attributes:

    system_prompt: str
        Depending on the judgment representation, this system prompt
        instructs the LLM on how to generate judgments in the corresponding format,
        such as JSON-based judgments, python code, etc.

    user_prompt_template: str
        A template string that is used to generate a user prompt for the LLM,
        and had format keys for `observation` and `instruction`.

    """

    system_prompt = SYSTEM_PROMPT
    user_prompt_template = USER_PROMPT_TEMPLATE
